# Generated by Django 2.1.3 on 2018-12-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.CharField(max_length=20)),
                ('tipo_despesa', models.CharField(choices=[('RM', 'Remedio'), ('RP', 'Roupas'), ('AL', 'Alimentacao'), ('ED', 'Educacao'), ('TP', 'Transporte'), ('OU', 'Outros')], max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('forma_pagamento', models.CharField(choices=[('DN', 'Dinheiro'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('CCR', 'Cartao de Crediário'), ('CH', 'Cheque')], max_length=30)),
                ('vencimento', models.DateField()),
                ('quitado', models.BooleanField()),
            ],
            options={
                'ordering': ('-vencimento', 'forma_pagamento'),
            },
        ),
    ]
