# Generated by Django 2.1.4 on 2018-12-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleGasto', '0003_auto_20181222_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='vencimento',
            field=models.DateField(),
        ),
    ]
