# Generated by Django 2.1.4 on 2018-12-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleGasto', '0005_auto_20181231_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='vencimento',
            field=models.DateField(),
        ),
    ]
